### ISSUE TITLE
Integrate with hasura.io

### ISSUE THREAD

**Issue by BenHizak** [IvanGoncharov/graphql-voyager#114]
Cherre uses Hasura.io (a graphql <--> Postgres layer). It would be great to build voyager into Hasura's web interface.

The team behind Hasura are pretty friendly and are available on [this discord channel](https://discord.gg/vBPpJkS). I am happy to make intros.

**Comment by mnlbox** [comment]
@BenHizak They also have some work about this but it's not finished yet:
https://github.com/hasura/graphql-engine/pull/799

I think if someone from voyager community join that PR we can see this integration soon.

Other related issue:
https://github.com/hasura/graphql-engine/issues/1731

**Comment by FluorescentHallucinogen** [comment]
Related issues:

* https://github.com/hasura/graphql-engine/issues/2128
* #120

**Comment by sanderhahn** [comment]
Would be convenient if there is an option to skip the aggregate types. Made a checkbox for this in the display options: [example](https://sander.io/voyager.html) in this commit https://github.com/sanderhahn/graphql-voyager/commit/4af5e829ad544f99b29981bd7e2c9164d74d87eb but i can understand that this filter is very Hasura specific.

**Comment by IvanGoncharov** [comment]
@sanderhahn We implemented a similar feature (skip all types that start with certain prefix) for one of our customers.
So even though your filter itself is Hasura-specific I believe we should provide some mechanism for embedding client-defined filters in Voyager.
It's definitely post-1.0.0 feature but can you please open an issue so we wouldn't forget about it?

**Comment by FluorescentHallucinogen** [comment]
This issue can be closed as done.
