### ISSUE TITLE
getJsUrl() clears a document via document.write()

### ISSUE THREAD

**Issue by Fi1osof** [IvanGoncharov/graphql-voyager#136]
If include graphql-voyager after load document (because SSR not works) getJsUrl calling clears a document via [document.write()](https://github.com/APIs-guru/graphql-voyager/blob/master/src/utils/index.ts#L44), because document.write works correctly only while DOM still in loading.

P.S. special "thanks" for try/catch with error hiding. 3 hours for debugging...

**Comment by borbea** [comment]
@Fi1osof I know this post is pretty old but did you maybe found a fix this? Or how to load Voyager component after the document. Thanks

**Comment by Fi1osof** [comment]
> @Fi1osof I know this post is pretty old but did you maybe found a fix this? Or how to load Voyager component after the document. Thanks

It's really pretty old... And probably i can't help. I create fork https://github.com/prisma-cms/graphql-voyager and rewrite many code. And then include in my project https://github.com/prisma-cms/front/blob/2.7.4/src/components/pages/GraphqlVoyager/index.js#L25

**Comment by IvanGoncharov** [comment]
@Fi1osof Thanks for reporting 👍 
Fixed in v1.0.0 since now worker is bundled into library.
