### ISSUE TITLE
Support AWS Appsync GraphQL ?

### ISSUE THREAD

**Issue by rberger** [IvanGoncharov/graphql-voyager#172]
Is there a way to use GraphQL-voyager with the AWS AppSync graphql custom directives?

**Comment by Booligoosh** [comment]
Managed to get it working with an AWS Amplify / AppSync schema. Rather than pasting the `schema.graphql` in the SDL tab, go to the Introspection tab, then paste the contents of your compiled `schema.json` file.

**Comment by espetro** [comment]
Hi @Booligoosh , I've tried to do that, but although the app doesn't comply, the resulting visualization is quite different from what I inputted:

![](https://i.imgur.com/AoY7oQI.png)

**Comment by marcoruizrueda** [comment]
Any update on supporting AWS AppSync directly?
