### ISSUE TITLE
Bug: Breaks with newer GraphQL spec support like interface inheritance

### ISSUE THREAD

**Issue by robross0606** [IvanGoncharov/graphql-voyager#224]
This repository hasn't been updated in two years, with no release in 5 years.  In the meantime, the spec has been updated to support things like [Interface inheritance](http://spec.graphql.org/draft/#sec-Interfaces.Interfaces-Implementing-Interfaces).  

```
voyager.min.js:82 Uncaught (in promise) Error: Interface field PaginatedObjects.results expects type [Object!]! but PagedStudyEventItemChildren.results is type [StudyEventItemChild!]!.
    at voyager.min.js:82:178434
    at voyager.min.js:82:178495
    at Mn (voyager.min.js:82:178663)
    at voyager.min.js:82:185786
    at Qn (voyager.min.js:82:185903)
    at cr (voyager.min.js:82:187521)
    at t.updateIntrospection (voyager.min.js:82:239299)
    at voyager.min.js:82:239160
```

Is this tool abandoned or are there plans to update it to support newer standards features?

**Comment by LunaticMuch** [comment]
It's resuming. Give us few weeks. 
Can you provide more info to reproduce this bug? An example schema would definitely help.

**Comment by robross0606** [comment]
Turns out the latest release candidate supported some of the newer spec features.  I just had to manually update to release candidate 31 to get them.
