### ISSUE TITLE
Live Demo is now giving 404

### ISSUE THREAD

**Issue by k4k4r07** [IvanGoncharov/graphql-voyager#226]
Live demo at https://apis.guru/graphql-voyager/ seems to be removed. Is this intended or will it be up again?

**Comment by FluorescentHallucinogen** [comment]
@k4k4r07 See https://ivangoncharov.github.io/graphql-voyager/. :wink:

**Comment by k4k4r07** [comment]
Thanks a lot @FluorescentHallucinogen
