### ISSUE TITLE
this schema makes voyager hang.

### ISSUE THREAD

**Issue by pvinis** [IvanGoncharov/graphql-voyager#254]
we tried giving this to the live demo, and it stayed on the "transmitting" animation forever. any ideas?

https://gist.githubusercontent.com/pvinis/01e6e67bfad6cf76839e5916f3fe1c52/raw/fcc26a1c4ec7f29b03ac88192f27f92f065aea22/gistfile1.txt

**Comment by IvanGoncharov** [comment]
@pvinis Fixed in v1.0.0
It takes 8s on my machine.
