### ISSUE TITLE
Typo in demo field name

### ISSUE THREAD

**Issue by vermiculus** [IvanGoncharov/graphql-voyager#86]
https://github.com/APIs-guru/graphql-voyager/blob/df0e86ec6d7cdfedb0382d5b357237254fc7bc09/demo/presets/github_introspection.json#L10623

This should be `targetUrl`. If this is a generated file, it should probably be re-generated.

**Comment by IvanGoncharov** [comment]
It's an introspection dump from GitHub, and we just provide it as an example.
Feel free to report it to GitHub itself.
